language: go
dist: trusty
sudo: false
go: "1.11"
services:
  - postgresql
addons:
env:
  global:
    - PATH=$PATH:$HOME/gopath/bin
    - GO111MODULE=on
before_install:
  - go get golang.org/x/tools/cmd/goimports
before_script:
  - psql -c 'ALTER USER postgres WITH SUPERUSER;'
  - psql -U postgres -c 'CREATE DATABASE coinsph;'
script:
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN:-"$CODE_COV_KEY"} || echo 'Codecov failed to upload.'
