// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
	entities "github.com/twonegatives/coinsph_challenge/pkg/entities"
	reflect "reflect"
)

// MockStorage is a mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method
func (m *MockStorage) CreateAccount(ctx context.Context, accountName string) (entities.Account, error) {
	ret := m.ctrl.Call(m, "CreateAccount", ctx, accountName)
	ret0, _ := ret[0].(entities.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount
func (mr *MockStorageMockRecorder) CreateAccount(ctx, accountName interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockStorage)(nil).CreateAccount), ctx, accountName)
}

// GetAccountsList mocks base method
func (m *MockStorage) GetAccountsList(ctx context.Context) ([]entities.Account, error) {
	ret := m.ctrl.Call(m, "GetAccountsList", ctx)
	ret0, _ := ret[0].([]entities.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsList indicates an expected call of GetAccountsList
func (mr *MockStorageMockRecorder) GetAccountsList(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsList", reflect.TypeOf((*MockStorage)(nil).GetAccountsList), ctx)
}

// GetPaymentsList mocks base method
func (m *MockStorage) GetPaymentsList(ctx context.Context) ([]entities.Payment, error) {
	ret := m.ctrl.Call(m, "GetPaymentsList", ctx)
	ret0, _ := ret[0].([]entities.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentsList indicates an expected call of GetPaymentsList
func (mr *MockStorageMockRecorder) GetPaymentsList(ctx interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentsList", reflect.TypeOf((*MockStorage)(nil).GetPaymentsList), ctx)
}

// SendPayment mocks base method
func (m *MockStorage) SendPayment(ctx context.Context, from, to entities.Account, amount decimal.Decimal) error {
	ret := m.ctrl.Call(m, "SendPayment", ctx, from, to, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPayment indicates an expected call of SendPayment
func (mr *MockStorageMockRecorder) SendPayment(ctx, from, to, amount interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPayment", reflect.TypeOf((*MockStorage)(nil).SendPayment), ctx, from, to, amount)
}
